# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        Ravedok\Shared\Domain\Bus\Command\CommandHandler:
            tags: 
                -
                    name: messenger.message_handler
                    bus: messenger.bus.commands
        
        Ravedok\Shared\Domain\Bus\Event\EventHandler:
            tags: 
                -
                    name: messenger.message_handler
                    bus: messenger.bus.events


    Ravedok\Apps\Catalog\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    Ravedok\Shared\:
        resource: '../../../src/Shared/'

    Ravedok\Catalog\:
        resource: '../../../src/Catalog/'


    Ravedok\Shared\Infrastructure\Bus\Event\SymfonyEventBus: 
        arguments: ['@messenger.bus.events']
    
