framework:
    messenger:
      default_bus: messenger.bus.commands
      buses:
        messenger.bus.commands: 
          middleware:
            - doctrine_ping_connection
            - doctrine_close_connection
            - doctrine_transaction
        messenger.bus.events: 
          default_middleware: allow_no_handlers
